// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace webone.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240930212503_Addseeds")]
    partial class Addseeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Departments", b =>
                {
                    b.Property<Guid>("Id_department")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<string>("Dep_manager")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Dep_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id_department");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id_department = new Guid("072fa384-7167-4fdd-bada-82c1fab0a936"),
                            Auto = 0,
                            Dep_manager = "Феликсов Алексей Сергеевич",
                            Dep_name = "финансовый отдел"
                        },
                        new
                        {
                            Id_department = new Guid("76ba7ada-5a47-43ff-bbf0-c6e7e0231cae"),
                            Auto = 0,
                            Dep_manager = "Кирьянов Алексей Сергеевич",
                            Dep_name = "финансовый отдел"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
