version: '3.7'

volumes:
  postgresql-vl:
  pgadmin-data:

networks:
  postgres:
    driver: bridge

services:
  postgresql-server:
    image: postgres:16
    restart: unless-stopped
    container_name: postgresql-server-container #host for pgadmin
    ports:
      - 5432:5432
    volumes:
      - postgresql-vl:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db-init"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db-init"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@psg.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      # admin password: password
      # dbname=postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
    depends_on:
      - postgresql-server